### ISSUE TITLE
How to restore single keyspace using medusa in k8ssandra cluster??

### ISSUE THREAD

**Issue by AkashRajvanshi** [k8ssandra/medusa-operator#24]
**Type of question**

- [ ] Best practices
- [ ] How to perform a particular operation
- [ ] Cassandra-related question
- [ ] Monitoring-related question
- [ ] Repair-related question
- [x ] Backup/restore-related question
Hey, I want to restore only a single keyspace from my s3 backup instead of the whole cluster. can you please help me with how can I back up and restore a particular keyspace using the medusa operator??
- [ ] Open question

**What did you do?**

**Did you expect to see something different?**

**Environment (please complete the following information):**

* medusa-operator version:

v0.1.0

* Helm charts version info 

`$ helm ls -A` 

* Helm charts user-supplied values

`$ helm get values RELEASE_NAME` 

* Kubernetes version information:

`kubectl version`

* Kubernetes cluster kind:

* Manifests:

* Operator logs:

`kubectl -n <namespace> logs -l name=<releaseName>-medusa-operator-k8ssandra`

**Additional context**

**Comment by jsanda** [comment]
Hi @AkashRajvanshi 

Medusa does not currently support backing up only a specific keyspace. If this is a feature you would like, then please open a feature request ticket in the k8ssandra repo.

I have already created https://github.com/k8ssandra/k8ssandra/issues/222 for partial restores.

**Comment by AkashRajvanshi** [comment]
Ok, Thank You :)
